# configs/callbacks/default.yaml
defaults:
  - model_checkpoint
  #- early_stopping
  - learning_rate_monitor
  - rich_progress_bar
  #- mlflow_model_tracking
  - model_saving_callback
  - audio_reconstruction_logging