# configs/callbacks/early_stopping.yaml
early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: val/total_loss
  mode: min
  patience: 20
  min_delta: 0.0
  check_finite: true
  verbose: true